package com.foodordering.model;

import com.foodordering.observer.OrderObserver;
import com.foodordering.state.OrderState;
import com.foodordering.state.PendingState;
import com.foodordering.strategy.DeliveryStrategy;

import java.util.ArrayList;
import java.util.List;

/**
 * Core domain class representing a food order.
 * Acts as the Context in the State pattern (delegates state-dependent behavior).
 * Acts as the Subject in the Observer pattern (notifies observers on state change).
 * Built step-by-step via the Builder pattern.
 */
public class Order {
    private String orderId;
    private Customer customer;
    private List<OrderItem> items;
    private DeliveryStrategy deliveryStrategy;
    private String paymentMethod;
    private double totalAmount;
    private OrderState currentState;
    private List<OrderObserver> observers;

    /**
     * Creates a new Order in PENDING state.
     * @param orderId  Unique order identifier (generated by builder)
     * @param customer The customer placing this order
     */
    public Order(String orderId, Customer customer) {
        this.orderId = orderId;
        this.customer = customer;
        this.items = new ArrayList<>();
        this.observers = new ArrayList<>();
        this.currentState = new PendingState();
    }

    public String getOrderId() { return orderId; }
    public Customer getCustomer() { return customer; }
    public List<OrderItem> getItems() { return items; }
    public DeliveryStrategy getDeliveryStrategy() { return deliveryStrategy; }
    public String getPaymentMethod() { return paymentMethod; }
    public double getTotalAmount() { return totalAmount; }
    public OrderState getCurrentState() { return currentState; }
    public String getStatus() { return currentState.getStatus(); }

    public void setItems(List<OrderItem> items) { this.items = items; }
    public void setDeliveryStrategy(DeliveryStrategy s) { this.deliveryStrategy = s; }
    public void setPaymentMethod(String paymentMethod) { this.paymentMethod = paymentMethod; }
    public void setTotalAmount(double totalAmount) { this.totalAmount = totalAmount; }

    /**
     * Changes the current state and notifies all observers.
     * Called by state implementations when a valid transition occurs.
     *
     * @param state The new state to transition to
     */
    public void setState(OrderState state) {
        this.currentState = state;
        notifyObservers("Order " + orderId + " status changed to: " + state.getStatus());
    }

    // --- Observer pattern methods ---

    public void attach(OrderObserver observer) {
        observers.add(observer);
    }

    public void detach(OrderObserver observer) {
        observers.remove(observer);
    }

    /** Notifies all registered observers with a status message. */
    public void notifyObservers(String message) {
        for (OrderObserver observer : observers) {
            observer.update(this, message);
        }
    }

    // --- State pattern delegates ---

    public void confirm() { currentState.confirm(this); }
    public void prepare() { currentState.prepare(this); }
    public void deliver() { currentState.deliver(this); }
    public void complete() { currentState.complete(this); }
    public void cancel() { currentState.cancel(this); }

    /** Adds an item during builder construction. */
    public void addItem(OrderItem orderItem) {
        items.add(orderItem);
    }

    /** @return Sum of all item totals before tax and delivery */
    public double calculateTotal() {
        return items.stream().mapToDouble(OrderItem::getTotalPrice).sum();
    }

    @Override
    public String toString() {
        return String.format("Order[%s] - %s - NPR %,.2f - %s",
                orderId, customer.getName(), totalAmount, currentState.getStatus());
    }
}
